In [114]:
# CAP 5630 HW4
# Josh E.

import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import os
import random

# assumes csv's are in the same directory
train_data = pd.read_csv(os.getcwd() + "\\data.csv", header=None)

for col in train_data.columns:
    if train_data.loc[:, col].mean() == 0 or train_data.loc[:, col].max == train_data.loc[:, col].min():
        train_data.drop(columns=[col], inplace=True)
train_data.columns = range(train_data.shape[1])

labels = pd.read_csv(os.getcwd() + "\\label.csv", header=None)

'''
K-Means Algorithm

Input: K, data matrix
Output: K centers, cluster number/labels of each point

Algorithm:

    1. Initialization:
        - Randomly select K points as K centers
    
    2. Repeat:
        - Assignment: Assign data points to K clusters based on distance between centers and points
        - Update: Compute the new centers(means)
        
    3. Stop Critera:
        - the centers/means do not change (the assignment does not change)

'''

from sklearn.metrics.pairwise import cosine_similarity

def k_means(K, dataset, labels, dist_function):
    
    # initialization
    centers = []
    for i in range(K):
        centers.append(dataset.iloc[math.floor(random.random() * dataset.shape[0])])
    centers = np.array(centers)
    dataset = dataset.to_numpy()
    labels = labels.to_numpy()
    
    # repeat
    while True:
        print("iteration start")
        clusters = []
        for i in range(centers.shape[0]):
            clusters.append(np.empty([0,dataset.shape[1]]))
        #print(np.reshape(dataset[0],(1, dataset.shape[1])).shape)
        
        for i in range(dataset.shape[0]):
            distances = []
            for j in range(K):
                distances.append(dist_function(dataset[i], centers[j]))
            cluster_index = distances.index(min(distances))
            clusters[cluster_index] = np.vstack((clusters[cluster_index], np.array(dataset[i])))
            
        '''for i in range(centers.shape[0]):
            print(clusters[i].shape)'''
        
        new_centers = np.zeros(centers.shape)
        for i in range(new_centers.shape[0]):
            new_centers[i] = np.floor(np.mean(clusters[i], axis=0))
        
        # stop criteria
        if (np.equal(centers, new_centers)).all():
            print(centers)
            print("loop end")
            break
        else:
            print(new_centers)
            print("end iteration")
            centers = new_centers 
            
    predicted_labels = []
    for i in range(dataset.shape[0]):
        distances = []
        for j in range(K):
            distances.append(dist_function(dataset[i], centers[j]))
        cluster_index = distances.index(min(distances))
        predicted_labels.append(cluster_index)
        
    from sklearn.metrics import accuracy_score
    
    print("Accuracy: ", accuracy_score(labels, predicted_labels))
    print("Accuracy: ", accuracy_score(predicted_labels, labels))
    
k_means(10, train_data, labels, math.dist)

iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0.

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
end iteration
iteration start
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0.

1.0